klister/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('klisterApp.urls')),
    path("admin/", admin.site.urls),
]

klisterApp/urls.py
from django.urls import path
from .views import create_form, change_filepath, change_password, SuccessView

urlpatterns = [

    path('', create_form, name='home'),
    path('change-filepath/', change_filepath, name='change_filepath'),
    path('change_password/', change_password, name='change_password'),
    path('success/', SuccessView.as_view(), name='success'),
    ]

klisterApp/models.py
from django.db import models

# Create your models here.

stadsdelar = [("Stadsområde Centrum", "Stadsområde Centrum"), ("Stadsområde Nordost", "Stadsområde Nordost"), ("Stadsområde Sydväst", "Stadsområde Sydväst"), ("Stadsområde Hisingen", "Stadsområde Hisingen")]


class formPage(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    stadsdel = models.CharField(max_length=21, choices=stadsdelar)
    idrott = models.CharField(max_length=100)
    önskad_idrott = models.CharField(max_length=100, verbose_name="Önskad idrott")
    in_a_union = models.BooleanField()
    filePath = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class password(models.Model):
    password = models.CharField(max_length=100)


class SpreadsheetId(models.Model):
    IDString = models.CharField(max_length=1024)
    gid = models.CharField(max_length=1024)

klisterApp/forms.py
from django import forms
from .models import formPage


class formPageForm(forms.ModelForm):
    class Meta:
        model = formPage
        fields = ['name', 'age', 'stadsdel', 'idrott', 'önskad_idrott', 'in_a_union']
        widgets = {
            'level': forms.Select(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'in_a_union': forms.CheckboxInput(attrs={'class': 'form-check-input', 'type': 'checkbox', 'role': 'switch'})
        }

klisterApp/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import password, SpreadsheetId
from .forms import formPageForm
from django.views.generic import CreateView
from .excel import add_row_to_google_sheets, extract_key_and_gid, get_sheet_name
from django.views.generic import TemplateView


main_path = None  # Retrieve the first instance of the formPage model
message = None


class SuccessView(TemplateView):
    template_name = 'success.html'


def create_form(request):
    global message
    addRowConfirmation = None
    # Set a default value for filePath
    spreadsheet_id = None
    spreadsheet_gid = None

    # Retrieve the file path from the FilePath model
    try:
        spreadSheet_instance = SpreadsheetId.objects.get(pk=1)  # Assuming the FilePath instance has primary key 1
        spreadsheet_id = spreadSheet_instance.IDString
        spreadsheet_gid = spreadSheet_instance.gid

    except SpreadsheetId.DoesNotExist:
        pass  # Handle the case when the FilePath instance does not exist
    is_error = message and message.startswith(" ")
    if request.method == 'POST':
        form = formPageForm(request.POST)
        print("posting")
        if form.is_valid():
            klisterData = {
                'name': form.cleaned_data['name'],
                'age': form.cleaned_data['age'],
                'stadsdel': form.cleaned_data['stadsdel'],
                'idrott': form.cleaned_data['idrott'],
                'önskad_idrott': form.cleaned_data['önskad_idrott'],
                'in_a_union': form.cleaned_data['in_a_union'],
            }
            print(klisterData)
            try:
                add_row_to_google_sheets(spreadsheet_id, klisterData, spreadsheet_gid)
                addRowConfirmation = klisterData['name'] + '(' + str(klisterData['age']) + ')' + " row added!"
                # Redirect to the success URL using reverse
                success_url = reverse('success')
                return redirect(success_url)
            except Exception as e:
                if "Read-only file system" in str(e):
                    message = " " + "Error: You do not have permission to write to this file"
                else:
                    message = " " + f"An error occurred: {str(e)}"
                return redirect('home')  # Redirect back to the form page with the error message

    else:
        form = formPageForm()

    return render(request, 'home.html', {'form': form, 'spreadsheet_id': get_sheet_name(spreadsheet_id, spreadsheet_gid), 'message': message, 'is_error': is_error})


def change_filepath(request):
    global message

    if request.method == 'POST':
        entered_password = request.POST.get('password')
        try:
            password_instance = password.objects.get(pk=1)  # Assuming the password instance has primary key 1
        except password.DoesNotExist:
            message = " " + "Password instance does not exist."
            return HttpResponseRedirect("/")

        if entered_password != password_instance.password:
            message = " " + "Invalid password. Please try again."
            return HttpResponseRedirect("/")
        else:
            spreadsheet_link = request.POST.get('spreadsheet_link')
            # Update or create the FilePath instance
            file_path_instance, created = SpreadsheetId.objects.update_or_create(pk=1, defaults={'IDString': extract_key_and_gid(spreadsheet_link)[0], 'gid': extract_key_and_gid(spreadsheet_link)[1], })
            message = 'File updated successfully.'
            return HttpResponseRedirect("/")


def change_password(request):
    global main_path  # Declare main_path as a global variable
    global message
    global excel_password
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        confirmed_password = request.POST.get('confirmed_password')

        # Retrieve the password instance from the database
        try:
            password_instance = password.objects.get(pk=1)  # Assuming the password instance has primary key 1
        except password.DoesNotExist:
            # If the password instance doesn't exist, create a new one with the provided new_password
            password_instance = password(password=new_password)
            password_instance.save()

        # Custom authentication logic for the password
        if old_password != password_instance.password:
            message = " " + 'Old password does not match!'
            return HttpResponseRedirect("/")
        elif new_password != confirmed_password:
            message = " " + 'New passwords do not match!'
            return HttpResponseRedirect("/")
        else:
            password_instance.password = new_password
            password_instance.save()
            message = 'Password changed successfully!'
            return HttpResponseRedirect("/")


"""def modalErrorMessage(messageString):
    # Handle when the password instance does not exist.
    message = " " + messageString
    return HttpResponseRedirect("/")

def modalSuccessMessage(message, messageString):
    # Handle when the password instance does not exist.
    message = " " + messageString
    return HttpResponseRedirect("/")"""

templates/base.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Tjejsatsningen{% endblock %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/images.css' %}">

</head>

<body data-bs-theme="dark">
  <div class="container-sm" style="padding-top: 100px;">
    <main class="container-sm text-center">
      {% block content %}
      {% endblock %}
      {% include 'pathModal.html' %}
    </main>
    <div class="container text-center">
      <footer>
        <p>&copy; Powered by 
          <img src="{% static 'img/colonfour.png' %}" class="rounded custom-image" alt="...">
        </p>
      </footer>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>
  <script>
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
  </script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-end mb-4">
    <button type="button" class="btn btn-outline-secondary ml-auto" data-bs-toggle="modal"
        data-bs-target="#pathModal">
        Sheet name: {{ spreadsheet_id }}
    </button>
    <button type="button" class="btn btn-outline-secondary ml-2" data-bs-toggle="modal"
        data-bs-target="#passwordModal">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-shield-lock-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                d="M8 0c-.69 0-1.843.265-2.928.560-1.11.300-2.229.655-2.887.870a1.54 1.54 0 0 0-1.044 1.262c-.596 4.477.787 7.795 2.465 9.990a11.777 11.777 0 0 0 2.517 2.453c.386.273.744.482 1.048.625.28.132.581.24.829.24s.548-.108.829-.240a7.159 7.159 0 0 0 1.048-.625 11.775 11.775 0 0 0 2.517-2.453c1.678-2.195 3.061-5.513 2.465-9.990a1.541 1.541 0 0 0-1.044-1.263 62.467 62.467 0 0 0-2.887-.870C9.843.266 8.69 0 8 0zm0 5a1.5 1.5 0 0 1 .5 2.915l.385 1.990a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.990A1.5 1.5 0 0 1 8 5z" />
        </svg>
    </button>
</div>

{% include 'pathModal.html' %}
{% include 'passwordModal.html' %}

<div class="row justify-content-center pr-sm-4">
    <div class="col-sm-6 col-md-4 mb-4" >
        <img src="{% static 'img/tjej.png' %}" class="rounded img-fluid" alt="...">
    </div>
</div>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-8 col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3 pt-3">
                    <label class="input-group-text" for="id_name">Namn</label>
                    <input type="text" class="form-control" name="name" id="id_name" required>
                </div>

                <div class="input-group mb-3">
                    <label class="input-group-text" for="id_age">Ålder</label>
                    <input type="number" class="form-control" name="age" id="id_age" required>
                </div>

                <div class="input-group mb-3">
                    <label class="input-group-text" for="{{ form.stadsdel.id_for_label }}" data-bs-toggle="popover"
                           data-bs-placement="left" title="Popover Title" data-bs-content="baby">Stadsdel</label>
                    <select class="form-control" name="{{ form.stadsdel.html_name }}" id="{{ form.stadsdel.auto_id }}" {% if form.stadsdel.multiple %}multiple{% endif %}>
                        {% for value, display_name in form.stadsdel.field.choices %}
                            <option value="{{ value }}"{% if value in form.stadsdel.value %} selected{% endif %}>{{ display_name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <p class="lead pr-sm-4" style="font-size: 12px;">
                    Du kan kolla <a
                        href="https://goteborg.se/wps/portal/start/kommun-och-politik/om-goteborg/stadsomraden-och-mellanomraden">här</a>
                    för att veta vilken är ditt stadsdel.
                </p>

                <div class="input-group mb-3 pt-1">
                    <label class="input-group-text" for="id_idrott">Idrott</label>
                    <input type="text" class="form-control" name="idrott" id="id_idrott" required>
                </div>

                <div class="input-group mb-3">
                    <label class="input-group-text" for="id_önskad_idrott">Önskad Idrott</label>
                    <input type="text" class="form-control" name="önskad_idrott" id="id_önskad_idrott" required>
                </div>

                <div class="form-check form-switch mb-3">
                    <input class="form-check-input" type="checkbox" name="in_a_union" id="id_in_a_union">
                    <label class="form-check-label" for="id_in_a_union">Förening?</label>
                </div>

                <button type="submit" class="btn btn-outline-success">Klar</button>

                {% if message %}
                {% if is_error %}
                <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endif %}
            </form>
        </div>
    </div>
</div>

<br>
<script src="{% static 'js/modalsAlerts.js' %}"></script>
{% endblock %}

templates/passwordModal.html
<!-- Modal -->
<div class="modal fade" id="passwordModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Change Password</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'change_password' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="id_password"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                          </svg></label>
                        <input type="password" class="form-control" id="id_password" name="old_password" placeholder="Enter the old password..." required>
                    </div>
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="id_password"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock" viewBox="0 0 16 16">
                            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2zM5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z"/>
                          </svg></label>
                        <input type="password" class="form-control" id="id_password" name="new_password" placeholder="Enter the new password..." required>
                    </div>
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="id_password"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                          </svg></label>
                        <input type="password" class="form-control" id="id_password" name="confirmed_password" placeholder="Confirm the new password..." required>
                    </div>

                    <div class="input-group mb-3">
                        <input class="form-control" type="text" value="xscellapp@xscellnew.iam.gserviceaccount.com" data-bs-toggle="popover"
                            data-bs-placement="left" data-bs-content="Add this email to the people with access to your spreadsheet" aria-label="service account email"
                            id="serviceAccountEmailInput" readonly>
                        <button class="btn btn-outline-secondary" type="button" id="copyServiceEmailButton">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                                <path
                                    d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z" />
                                <path
                                    d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z" />
                            </svg>
                        </button>
                    </div>
                      
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>



<script>
    function copyToClipboard(buttonName, inputFieldName) {
        // Get the input element
        const inputElement = document.getElementById(inputFieldName);

        // Select the text inside the input
        inputElement.select();

        // Copy the selected text to clipboard
        document.execCommand("copy");

        // Remove the selection (optional)
        window.getSelection().removeAllRanges();
    }

    // Add onclick event to the button
    document.getElementById("copyServiceEmailButton").onclick = function() {
        copyToClipboard("copyServiceEmailButton", "serviceAccountEmailInput");
    };
</script>

templates/pathModal.html
<!-- Modal -->
<div class="modal fade" id="pathModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Enter Sheet link and Password</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'change_filepath' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="id_filePath"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-spreadsheet" viewBox="0 0 16 16">
                            <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V9H3V2a1 1 0 0 1 1-1h5.5v2zM3 12v-2h2v2H3zm0 1h2v2H4a1 1 0 0 1-1-1v-1zm3 2v-2h3v2H6zm4 0v-2h3v1a1 1 0 0 1-1 1h-2zm3-3h-3v-2h3v2zm-7 0v-2h3v2H6z"/>
                          </svg></label>
                        <input type="text" class="form-control" id="id_filePath" name="spreadsheet_link" required>
                    </div>
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="id_password"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                          </svg></label>
                        <input type="password" class="form-control" id="id_password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/success.html
{% extends 'base.html' %}

{% block title %}Page Title{% endblock %}

{% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-12 text-center">
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    <br>
    <br>
    <h2 class="mt-2">Stäng gärna fönstret</h2>
  </div>
</div>
{% endblock %}